-- Reset: Drop table if it exists so we can recreate it cleanly
drop table if exists posts cascade;

-- Create the posts table
create table posts (
  id bigint generated by default as identity primary key,
  content text not null,
  user_email text, -- We can store email or display name
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table posts enable row level security;

-- Policy: Allow everyone to read posts (Public Read)
create policy "Public posts are viewable by everyone"
  on posts for select
  to anon, authenticated
  using ( true );

-- Policy: Allow authenticated users to insert posts (Private Write)
create policy "Authenticated users can insert posts"
  on posts for insert
  to authenticated
  with check ( auth.uid() = user_id );

-- Optional: Realtime
-- To enable realtime, you usually need to enable replication on the table
alter publication supabase_realtime add table posts;
