-- Create a table for post reactions
create table post_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  emoji_type text not null, -- 'like', 'heart', 'fire'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id, emoji_type) -- One reaction per type per user per post
);

-- Enable RLS
alter table post_reactions enable row level security;

-- Policies
create policy "Everyone can view reactions"
  on post_reactions for select
  using ( true );

create policy "Authenticated users can insert reactions"
  on post_reactions for insert
  to authenticated
  with check ( auth.uid() = user_id );

create policy "Users can delete their own reactions"
  on post_reactions for delete
  to authenticated
  using ( auth.uid() = user_id );
