-- Create a table for tracking visits
create table visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- Nullable (for guests)
  page_path text,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table visits enable row level security;

-- Allow everyone to insert (log visits)
create policy "Everyone can log visits"
  on visits for insert
  with check ( true );

-- Allow everyone to read visits (for the Admin Dashboard demo)
-- In a real app, you might restrict this to admins only
create policy "Everyone can view visits"
  on visits for select
  using ( true );
